---
DNS1:
  10.10.215.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: 10.10.215.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
serviceDns:
  loadBalancerIP: 10.10.215.250
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer
replicaCount: 1
